name: Auto-approve and Auto-merge Dependabot PRs

on:
  pull_request:
    branches:
      - master

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-approve Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
